#
# Makefile for some libs needed in the kernel.
#
# Note! Dependencies are done automagically by 'make dep', which also
# removes any old dependencies. DON'T put your own dependencies here
# unless it's something special (ie not a .c file).
#

L_TARGET := libps.a

obj-y += startup.o symusr.o stdef1.o stdef2.o stdef3.o \
	 stdef4.o stdef5.o stdef6.o stdef7.o stdef8.o

include $(TOPDIR)/Rules.make
